apiVersion: v2
name: remnawave-subscription-page
description: Helm chart for Remnawave subscription page
type: application
version: 0.3.0
appVersion: "8.0.0"
keywords:
  - remnawave
  - vpn
  - subscription
home: https://docs.rw
sources:
  - https://github.com/remnawave/subscription-page
maintainers:
  - name: Davydov Denis
    email: krotenot015@gmail.com
